defaults: &defaults
  library_path: '/Users/vova/Music'
  import_sources:
    - '/Users/vova'

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
  library_path: '/Users/vova/Projects/MusicLibrary/backend-rails/tmp'
