defaults: &defaults
  library_path: '/Users/vova/Music'
  import_sources:
    - '/Users/vova/Downloads'
    - '/Volumes/MUSIC'

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
  library_path: <%= ENV['MUSIC_LIBRARY'] %>
