defaults: &defaults
  library_path: '/Users/vova/Music/_'
  import_sources:
    - 'fs'

development:
  <<: *defaults

production:
  library_path: <%= ENV['MUSIC_LIBRARY'] %>
  import_sources:
    - 'fs'

test:
  <<: *defaults
  library_path: <%= ENV['MUSIC_LIBRARY'] %>
