defaults: &defaults
  library_path: '/Users/vova/Music/Library'
  import_sources:
    - '/Users/vova/Music'
    - '/Users/vova/Public'
    - '/Users/vova/mnt'

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
